/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint/suspicious/noEmptyBlockStatements: Auto-generated file
export {}
declare global {}
