export const ADULT_KEYWORDS = `
	色情, 黄色, 成人, 裸体, 裸聊, 裸照, 裸露,
	性爱, 做爱, 性交, 交配, 性行为, 性生活, 性服务,
	约炮, 一夜情, 419, 炮友, 床伴, 性伴侣,
	援交, 包养, 外围, 外围女, 楼凤, 小姐, 鸡, 妓女, 卖淫, 嫖娼,
	上门服务, 特殊服务, 全套服务, 按摩服务, 保健按摩,
	视频聊天, 裸聊, 视频秀, 直播秀, 福利视频, 福利姬,
	写真, 私房照, 艳照, 诱惑, 挑逗, 勾引, 撩人,
	AV, A片, 毛片, 黄片, 色片, 成人片, 成人电影, 成人视频,
	乳交, 口交, 肛交, 指交, 足交, 手交, 颜射, 內射, 中出, 口爆,
	自慰, 手淫, 打飞机, 撸管, 自摸, 自拍, 偷拍,
	性玩具, 情趣用品, 飞机杯, 充气娃娃, 震动棒, 跳蛋, 按摩棒,
	巨乳, 爆乳, 美乳, 丰满, 大胸, 翘臀, 美腿, 丝袜, 黑丝, 白丝,
	比基尼, 泳装, 内衣, 情趣内衣, 透视装, 和服, 制服, 女仆装, 护士装,
	处女, 处男, 破处, 初夜, 萝莉, 御姐, 人妻, 熟女, 少妇,
	中文字幕, 无码, 有码, 车震, 厕所, 更衣室, 试衣间,
	群交, 3P, 4P, 多P, 乱交, 换妻, 夫妻交换,
	SM, 虐待, 捆绑, 调教, 奴隶, 主人, 女王,
	兽交, 人兽, 恋童, 幼女, 萝莉控, 正太,

	黃色, 裸體, 性愛, 做愛, 性行為, 性服務, 約炮,
  性伴侶, 包養, 外圍, 外圍女, 樓鳳, 雞, 賣淫,
  上門服務, 特殊服務, 全套服務, 按摩服務, 視頻聊天, 視頻秀, 福利視頻,
  寫真, 艷照, 誘惑, 黃片, 成人電影, 成人視頻, 顏射,
  打飛機, 擼管, 飛機杯, 充氣娃娃, 震動棒, 豐滿, 翹臀,
  絲襪, 黑絲, 白絲, 泳裝, 內衣, 情趣內衣, 透視裝,
  女僕裝, 護士裝, 處女, 處男, 破處, 蘿莉, 少婦,
  無碼, 有碼, 車震, 廁所, 試衣間, 亂交,換妻, 夫妻交換,
  捆綁, 調教, 奴隸, 獸交, 人獸, 戀童, 蘿莉控,

	アダルト, エロ, エッチ, ポルノ, わいせつ, 猥褻,
	セックス, 性交, 性行為, エッチ, Hな, いやらしい,
	ヌード, 裸, 全裸, 半裸, 露出,
	AV, アダルトビデオ, エロ動画, エロ画像, エロ漫画,
	風俗, ソープ, ヘルス, デリヘル, ピンサロ, キャバクラ, ガールズバー,
	援助交際, 援交, パパ活, 愛人, セフレ, 不倫,
	オナニー, 自慰, 手コキ, フェラ, クンニ, パイズリ,
	巨乳, 爆乳, 美乳, 貧乳, 美尻, 美脚, 美少女,
	制服, コスプレ, メイド, ナース, OL, 女子高生, JK,
	ロリ, ロリコン, 熟女, 人妻, 未亡人, 痴女,
	無修正, モザイク, 裏ビデオ, 盗撮, 隠し撮り,
	SM, 緊縛, 調教, 奴隷, 女王様, M女, S女,
	乱交, 3P, 4P, スワッピング, 輪姦,
	獣姦, スカトロ, 放尿, 脱糞, 嘔吐,

	porn, porno, pornography, xxx, adult, nsfw,
	sex, sexual, sexy, erotic, nude, naked, nudity,
	fuck, fucking, fucked, screw, bang, shag,
	cock, dick, penis, pussy, vagina, cunt, ass, butt, boobs, tits, breasts,
	blowjob, handjob, footjob, titjob, anal, oral,
	masturbate, masturbation, jerk off, wank,
	orgasm, climax, cum, cumshot, creampie, facial,
	escort, prostitute, hooker, call girl, brothel, massage parlor,
	webcam, cam girl, live show, strip, striptease, stripper,
	hentai, doujin, ecchi, yaoi, yuri,
	jav, av idol, gravure,
	milf, cougar, teen, barely legal, virgin,
	bdsm, bondage, domination, submission, slave, master, mistress,
	fetish, kink, kinky, pervert, perversion,
	orgy, gangbang, threesome, foursome, group sex, swinger,
	incest, taboo, forbidden,
	rape, molest, abuse, assault
`;
