export const FRAUD_KEYWORDS = `
  刷单, 刷单兼职, 刷信誉, 刷好评, 刷流量, 刷粉丝, 刷点赞,
	兼职日结, 兼职高薪, 在家兼职, 网络兼职, 手机兼职,
	高额回报, 高收益, 稳赚不赔, 保本保息, 无风险, 零风险,
	投资理财, 炒外汇, 炒原油, 炒白银, 炒比特币, 数字货币, 虚拟币,
	传销, 拉人头, 下线, 上线, 层级返利,
	网赚, 网络赚钱, 在家赚钱, 躺赚, 睡后收入,
	贷款, 无抵押贷款, 黑户贷款, 秒批贷款, 套现, 信用卡套现,
	黑客, hack, hacker, 黑客接单, 黑客服务,
	代查, 查开房, 查酒店, 查通话记录, 查银行流水, 查户籍,
	定位找人, 手机定位, GPS定位, 实时定位,
	私家侦探, 调查公司, 婚外情调查, 婚姻调查,
	办证, 办理证件, 假证, 假学历, 假毕业证, 假学位证,
	代办, 包过, 包拿证, 无需考试,
	发票, 代开发票, 增值税发票, 普通发票, 专用发票,
	假币, 假钞, 假人民币, 假美元,

	刷單, 刷單兼職, 刷信譽, 刷好評, 刷流量, 刷粉絲, 刷點讚,
	兼職日結, 兼職高薪, 在家兼職, 網絡兼職, 手機兼職,
	高額回報, 穩賺不賠, 無風險, 零風險, 駭客, 駭客接單, 駭客服務,
	投資理財, 炒外匯, 炒白銀, 炒比特幣, 數字貨幣, 虛擬幣,
	傳銷, 拉人頭, 下線, 上線, 層級返利, 假幣, 假鈔, 假人民幣, 假美元,
	網賺, 網絡賺錢, 在家賺錢, 躺賺, 睡後收入, 手機定位, 實時定位,
	貸款, 無抵押貸款, 黑戶貸款, 秒批貸款, 套現, 信用卡套現,
	查開房, 查酒店, 查通話記錄, 查銀行流水, 查戶籍,
	私家偵探, 調查公司, 婚外情調查, 婚姻調查, 發票, 代開發票,
	辦證, 辦理證件, 假證, 假學歷, 假畢業證, 假學位證,
	代辦, 包過, 包拿證, 無需考試, 普通發票, 專用發票, 增值稅發票,

	詐欺, サギ, 振り込め詐欺, オレオレ詐欺, 架空請求,
	副業, 在宅ワーク, 簡単に稼げる, 高収入, 高額報酬,
	投資, FX, 仮想通貨, ビットコイン, 暗号資産,
	マルチ商法, ねずみ講, ネットワークビジネス, MLM,
	闇金, ヤミ金, 高利貸, ブラックリスト,
	ハッカー, 不正アクセス, なりすまし,
	偽造, 偽札, 偽造通貨, 偽証明書, 偽学歴,

	scam, fraud, phishing, phish, ponzi, pyramid scheme,
	get rich quick, make money fast, easy money, passive income,
	work from home, online job, side hustle,
	high return, guaranteed profit, no risk, risk free,
	forex, crypto trading, binary options, investment opportunity,
	hacker for hire, hack service, hire a hacker,
	fake id, fake passport, fake diploma, fake certificate,
	counterfeit, fake money, fake currency,
	money laundering, wire transfer, western union
`;
