-- ============================================
-- 短链接服务数据库架构 (使用 Supabase Auth)
-- 版本: 2.0 - 支持高级链接配置
-- ============================================

-- 1. 用户扩展信息表 (关联 Supabase auth.users)
-- Supabase Auth 已经提供了 auth.users 表，我们只需要扩展用户信息
create table public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  avatar_url text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- 2. 短链接表 (添加 user_id 关联和高级配置字段)
create table public.links (
  id bigint generated by default as identity not null,
  user_id uuid references auth.users(id) on delete cascade,  -- 关联 Supabase Auth
  link text not null,
  short text not null unique,  -- 短链接哈希值，全局唯一
  title text,  -- 可选: 链接标题
  description text,  -- 可选: 链接描述
  expiration_date timestamp with time zone,  -- 过期时间
  is_active boolean default true,  -- 是否启用
  password_hash text,  -- 可选: 访问密码 (bcrypt hash)
  max_clicks integer,  -- 可选: 最大点击次数限制
  click_count integer default 0,  -- 点击次数缓存，通过触发器自动更新
  -- 新增: 重定向配置
  redirect_type smallint default 302,  -- 重定向类型: 301(永久), 302(临时), 307(临时-保持方法), 308(永久-保持方法)
  -- 新增: 参数透传配置
  pass_query_params boolean default false,  -- 是否透传 URL 参数到目标链接
  -- 新增: Header 转发配置
  forward_headers boolean default false,  -- 是否转发指定的请求头
  forward_header_list jsonb default '[]'::jsonb,  -- 需要转发的请求头列表 (JSON 数组)
  -- 新增: 访问限制配置
  access_restrictions jsonb default '{}'::jsonb,  -- 访问限制配置 (JSON 对象)
  -- 时间戳
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint links_pkey primary key (id),
  constraint chk_redirect_type check (redirect_type in (301, 302, 307, 308))
);

-- 3. 过期时间选项表 (预设选项)
create table public.expiration_options (
  id bigint generated by default as identity not null,
  name text not null,
  days integer null,  -- 天数，用于天级别的过期时间配置
  hours integer null,  -- 小时数，用于小时级别的过期时间配置
  is_permanent boolean null default false,
  sort_order integer default 0,
  constraint expiration_options_pkey primary key (id)
);

-- 4. 访问日志表
create table public.link_access_logs (
  id bigint generated by default as identity not null,
  link_id bigint not null,
  accessed_at timestamp with time zone not null default now(),
  ip_address text,
  user_agent text,
  referrer text,
  country text,  -- 可选: 国家代码 (如 CN, US)
  city text,     -- 可选: 城市
  device_type text,  -- 设备类型: mobile/desktop/tablet
  browser text,  -- 浏览器名称
  os text,  -- 操作系统
  constraint link_access_logs_pkey primary key (id),
  constraint link_access_logs_link_id_fkey foreign key (link_id)
    references links (id) on delete cascade
);

-- ============================================
-- 索引优化
-- ============================================

-- links 表索引
create unique index idx_links_short on public.links(short);
create index idx_links_user_id on public.links(user_id);
create index idx_links_created_at on public.links(created_at desc);
create index idx_links_is_active on public.links(is_active) where is_active = true;
create index idx_links_redirect_type on public.links(redirect_type);
create index idx_links_expiration on public.links(expiration_date) where expiration_date is not null;

-- user_profiles 表索引
create index idx_user_profiles_username on public.user_profiles(username);

-- link_access_logs 表索引
create index idx_link_access_logs_link_id on public.link_access_logs(link_id);
create index idx_link_access_logs_accessed_at on public.link_access_logs(accessed_at desc);
create index idx_link_access_logs_device_type on public.link_access_logs(device_type);
create index idx_link_access_logs_country on public.link_access_logs(country);

-- ============================================
-- Row Level Security (RLS) 策略
-- ============================================

-- 启用 RLS
alter table public.user_profiles enable row level security;
alter table public.links enable row level security;
alter table public.link_access_logs enable row level security;

-- user_profiles 策略
create policy "用户可以查看自己的资料"
  on public.user_profiles for select
  using (auth.uid() = id);

create policy "用户可以更新自己的资料"
  on public.user_profiles for update
  using (auth.uid() = id);

create policy "用户可以插入自己的资料"
  on public.user_profiles for insert
  with check (auth.uid() = id);

-- links 表策略
create policy "任何人都可以通过 short 查询短链接"
  on public.links for select
  using (true);  -- 公开访问，用于重定向

create policy "用户只能查看自己的链接列表"
  on public.links for select
  using (auth.uid() = user_id);

create policy "认证用户可以创建短链接"
  on public.links for insert
  with check (auth.uid() = user_id);

create policy "用户只能更新自己的链接"
  on public.links for update
  using (auth.uid() = user_id);

create policy "用户只能删除自己的链接"
  on public.links for delete
  using (auth.uid() = user_id);

-- 允许匿名用户创建短链接 (可选，根据业务需求)
create policy "匿名用户可以创建短链接"
  on public.links for insert
  with check (user_id is null);

-- link_access_logs 策略
create policy "链接所有者可以查看访问日志"
  on public.link_access_logs for select
  using (
    exists (
      select 1 from public.links
      where links.id = link_access_logs.link_id
      and links.user_id = auth.uid()
    )
  );

create policy "任何人都可以插入访问日志"
  on public.link_access_logs for insert
  with check (true);  -- 公开插入，用于记录访问

-- ============================================
-- 触发器和函数
-- ============================================

-- 自动更新 updated_at 字段
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_updated_at
  before update on public.user_profiles
  for each row
  execute function public.handle_updated_at();

create trigger set_updated_at
  before update on public.links
  for each row
  execute function public.handle_updated_at();

-- 自动创建用户 profile
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.user_profiles (id, username)
  values (
    new.id,
    new.raw_user_meta_data->>'username'
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

-- 自动更新点击次数
create or replace function public.increment_click_count()
returns trigger as $$
begin
  update public.links
  set click_count = click_count + 1
  where id = new.link_id;
  return new;
end;
$$ language plpgsql;

create trigger on_link_access
  after insert on public.link_access_logs
  for each row
  execute function public.increment_click_count();

-- ============================================
-- 初始数据
-- ============================================

-- 插入过期时间选项
insert into public.expiration_options (name, days, hours, is_permanent, sort_order) values
  ('1小时', null, 1, false, 1),
  ('6小时', null, 6, false, 2),
  ('12小时', null, 12, false, 3),
  ('1天', 1, null, false, 4),
  ('3天', 3, null, false, 5),
  ('7天', 7, null, false, 6),
  ('14天', 14, null, false, 7),
  ('30天', 30, null, false, 8),
  ('90天', 90, null, false, 9),
  ('180天', 180, null, false, 10),
  ('365天', 365, null, false, 11),
  ('永久', null, null, true, 12);

-- ============================================
-- 视图 (便于统计查询)
-- ============================================

-- 用户链接统计视图
create or replace view public.user_link_stats as
select
  l.user_id,
  count(l.id) as total_links,
  sum(l.click_count) as total_clicks,
  count(case when l.created_at >= now() - interval '7 days' then 1 end) as weekly_new_links,
  round(avg(l.click_count), 2) as avg_clicks_per_link
from public.links l
where l.user_id is not null
group by l.user_id;

-- 链接详细统计视图
create or replace view public.link_stats as
select
  l.id,
  l.short,
  l.link,
  l.user_id,
  l.created_at,
  l.click_count,
  l.is_active,
  l.expiration_date,
  l.redirect_type,
  l.pass_query_params,
  l.forward_headers,
  l.max_clicks,
  count(distinct date_trunc('day', lal.accessed_at)) as active_days,
  count(distinct lal.ip_address) as unique_visitors,
  count(lal.id) as total_accesses
from public.links l
left join public.link_access_logs lal on l.id = lal.link_id
group by l.id, l.short, l.link, l.user_id, l.created_at, l.click_count,
         l.is_active, l.expiration_date, l.redirect_type, l.pass_query_params,
         l.forward_headers, l.max_clicks;

-- ============================================
-- 注释
-- ============================================

comment on table public.user_profiles is '用户扩展信息表，关联 Supabase auth.users';
comment on table public.links is '短链接表，支持用户关联、匿名创建和高级配置';
comment on table public.link_access_logs is '访问日志表，记录每次短链接访问';
comment on table public.expiration_options is '过期时间预设选项';

comment on column public.links.user_id is '关联 auth.users.id，null 表示匿名创建';
comment on column public.links.short is '短链接哈希值，全局唯一';
comment on column public.links.password_hash is '可选的访问密码 (bcrypt hash)';
comment on column public.links.max_clicks is '可选的最大点击次数限制';
comment on column public.links.click_count is '点击次数缓存，通过触发器自动更新';
comment on column public.links.redirect_type is '重定向类型: 301(永久), 302(临时), 307(临时-保持方法), 308(永久-保持方法)';
comment on column public.links.pass_query_params is '是否透传 URL 参数到目标链接';
comment on column public.links.forward_headers is '是否转发指定的请求头';
comment on column public.links.forward_header_list is '需要转发的请求头列表 (JSON 数组)，例如: ["User-Agent", "Accept-Language"]';
comment on column public.links.access_restrictions is '访问限制配置 (JSON 对象)，支持: ip_whitelist, ip_blacklist, allowed_countries, blocked_countries, allowed_devices, allowed_referrers, blocked_referrers';

comment on column public.expiration_options.days is '天数，用于天级别的过期时间配置';
comment on column public.expiration_options.hours is '小时数，用于小时级别的过期时间配置';

comment on column public.link_access_logs.device_type is '设备类型: mobile, tablet, desktop';
comment on column public.link_access_logs.country is '国家代码，如 CN, US, JP 等';

-- ============================================
-- access_restrictions JSON 结构说明
-- ============================================
-- {
--   "ip_whitelist": ["192.168.1.0/24", "10.0.0.1"],     -- IP 白名单，支持 CIDR
--   "ip_blacklist": ["1.2.3.4"],                         -- IP 黑名单
--   "allowed_countries": ["CN", "US", "JP"],             -- 允许的国家代码
--   "blocked_countries": ["RU"],                         -- 禁止的国家代码
--   "allowed_devices": ["mobile", "desktop", "tablet"],  -- 允许的设备类型
--   "allowed_referrers": ["google.com", "baidu.com"],    -- 允许的来源域名
--   "blocked_referrers": ["spam.com"]                    -- 禁止的来源域名
-- }
