-- ============================================
-- 短链接服务数据库架构 (使用 Supabase Auth)
-- ============================================

-- 1. 用户扩展信息表 (关联 Supabase auth.users)
-- Supabase Auth 已经提供了 auth.users 表，我们只需要扩展用户信息
create table public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  avatar_url text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

-- 2. 短链接表 (添加 user_id 关联)
create table public.links (
  id bigint generated by default as identity not null,
  user_id uuid references auth.users(id) on delete cascade,  -- 关联 Supabase Auth
  link text not null,
  short text not null unique,  -- 添加唯一约束
  title text,  -- 可选: 链接标题
  description text,  -- 可选: 链接描述
  expiration_date timestamp with time zone,  -- 过期时间
  is_active boolean default true,  -- 是否启用
  password_hash text,  -- 可选: 访问密码
  max_clicks integer,  -- 可选: 最大点击次数限制
  click_count integer default 0,  -- 点击次数缓存
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint links_pkey primary key (id)
);

-- 3. 过期时间选项表 (预设选项)
create table public.expiration_options (
  id bigint generated by default as identity not null,
  name text not null,
  days integer null,
  is_permanent boolean null default false,
  sort_order integer default 0,
  constraint expiration_options_pkey primary key (id)
);

-- 4. 访问日志表
create table public.link_access_logs (
  id bigint generated by default as identity not null,
  link_id bigint not null,
  accessed_at timestamp with time zone not null default now(),
  ip_address text,
  user_agent text,
  referrer text,
  country text,  -- 可选: 国家
  city text,     -- 可选: 城市
  device_type text,  -- mobile/desktop/tablet
  browser text,
  os text,
  constraint link_access_logs_pkey primary key (id),
  constraint link_access_logs_link_id_fkey foreign key (link_id)
    references links (id) on delete cascade
);

-- ============================================
-- 索引优化
-- ============================================

-- links 表索引
create unique index idx_links_short on public.links(short);
create index idx_links_user_id on public.links(user_id);
create index idx_links_created_at on public.links(created_at desc);
create index idx_links_is_active on public.links(is_active) where is_active = true;

-- user_profiles 表索引
create index idx_user_profiles_username on public.user_profiles(username);

-- link_access_logs 表索引
create index idx_link_access_logs_link_id on public.link_access_logs(link_id);
create index idx_link_access_logs_accessed_at on public.link_access_logs(accessed_at desc);

-- ============================================
-- Row Level Security (RLS) 策略
-- ============================================

-- 启用 RLS
alter table public.user_profiles enable row level security;
alter table public.links enable row level security;
alter table public.link_access_logs enable row level security;

-- user_profiles 策略
create policy "用户可以查看自己的资料"
  on public.user_profiles for select
  using (auth.uid() = id);

create policy "用户可以更新自己的资料"
  on public.user_profiles for update
  using (auth.uid() = id);

create policy "用户可以插入自己的资料"
  on public.user_profiles for insert
  with check (auth.uid() = id);

-- links 表策略
create policy "任何人都可以通过 short 查询短链接"
  on public.links for select
  using (true);  -- 公开访问，用于重定向

create policy "用户只能查看自己的链接列表"
  on public.links for select
  using (auth.uid() = user_id);

create policy "认证用户可以创建短链接"
  on public.links for insert
  with check (auth.uid() = user_id);

create policy "用户只能更新自己的链接"
  on public.links for update
  using (auth.uid() = user_id);

create policy "用户只能删除自己的链接"
  on public.links for delete
  using (auth.uid() = user_id);

-- 允许匿名用户创建短链接 (可选，根据业务需求)
create policy "匿名用户可以创建短链接"
  on public.links for insert
  with check (user_id is null);

-- link_access_logs 策略
create policy "链接所有者可以查看访问日志"
  on public.link_access_logs for select
  using (
    exists (
      select 1 from public.links
      where links.id = link_access_logs.link_id
      and links.user_id = auth.uid()
    )
  );

create policy "任何人都可以插入访问日志"
  on public.link_access_logs for insert
  with check (true);  -- 公开插入，用于记录访问

-- ============================================
-- 触发器和函数
-- ============================================

-- 自动更新 updated_at 字段
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_updated_at
  before update on public.user_profiles
  for each row
  execute function public.handle_updated_at();

create trigger set_updated_at
  before update on public.links
  for each row
  execute function public.handle_updated_at();

-- 自动创建用户 profile
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.user_profiles (id, username)
  values (
    new.id,
    new.raw_user_meta_data->>'username'
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

-- 自动更新点击次数
create or replace function public.increment_click_count()
returns trigger as $$
begin
  update public.links
  set click_count = click_count + 1
  where id = new.link_id;
  return new;
end;
$$ language plpgsql;

create trigger on_link_access
  after insert on public.link_access_logs
  for each row
  execute function public.increment_click_count();

-- ============================================
-- 初始数据
-- ============================================

-- 插入过期时间选项
insert into public.expiration_options (name, days, is_permanent, sort_order) values
  ('1小时', 0, false, 1),  -- 特殊处理: days=0 表示小时
  ('1天', 1, false, 2),
  ('7天', 7, false, 3),
  ('30天', 30, false, 4),
  ('永久', null, true, 5);

-- ============================================
-- 视图 (便于统计查询)
-- ============================================

-- 用户链接统计视图
create or replace view public.user_link_stats as
select
  l.user_id,
  count(l.id) as total_links,
  sum(l.click_count) as total_clicks,
  count(case when l.created_at >= now() - interval '7 days' then 1 end) as weekly_new_links,
  round(avg(l.click_count), 2) as avg_clicks_per_link
from public.links l
where l.user_id is not null
group by l.user_id;

-- 链接详细统计视图
create or replace view public.link_stats as
select
  l.id,
  l.short,
  l.link,
  l.user_id,
  l.created_at,
  l.click_count,
  count(distinct date_trunc('day', lal.accessed_at)) as active_days,
  count(distinct lal.ip_address) as unique_visitors,
  count(lal.id) as total_accesses
from public.links l
left join public.link_access_logs lal on l.id = lal.link_id
group by l.id, l.short, l.link, l.user_id, l.created_at, l.click_count;

-- ============================================
-- 注释
-- ============================================

comment on table public.user_profiles is '用户扩展信息表，关联 Supabase auth.users';
comment on table public.links is '短链接表，支持用户关联和匿名创建';
comment on table public.link_access_logs is '访问日志表，记录每次短链接访问';
comment on table public.expiration_options is '过期时间预设选项';

comment on column public.links.user_id is '关联 auth.users.id，null 表示匿名创建';
comment on column public.links.short is '短链接哈希值，全局唯一';
comment on column public.links.password_hash is '可选的访问密码 (bcrypt hash)';
comment on column public.links.max_clicks is '可选的最大点击次数限制';
comment on column public.links.click_count is '点击次数缓存，通过触发器自动更新';
